name: linux

on:
  push:
    branches: [ master ]

jobs:
  linux-test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: Install the zsh
      run: sudo apt update; sudo apt install zsh

    - name: Run init.sh
      run: ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Load .zshrc
      run: |
        zsh ~/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi