name: linux

on:
  push:
    branches: [ master ]

jobs:
  linux-test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: sudo apt update; sudo apt install zsh tmux shellcheck

    - name: Run init.sh
      run: ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Check .zshrc
      run: |
        zsh ~/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Check .vimrc
      run: |
        ex -c ":source ~/.vimrc|:q" 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi
    
    - name: Check .tmux.conf
      run: |
        tmux new-session -d; tmux source-file ~/.tmux.conf 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi