name: macos

on:
  push:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run init.sh
      run: ${GITHUB_WORKSPACE}/bin/init.sh

    - name: Load .zshrc
      run: |
        zsh ~/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi